### PR TITLE
Implement Telegram bot bee

### PR DESCRIPTION
**Pull request by lalotone**
Telegram bee that can send/receive messages to/from chats or groups.

### CODE REVIEW

**Comment by muesli** [comment]
Nice work, thanks for your contribution!

**Comment by muesli** [comment]
Feel like updating our wiki to include the TelegramBee, too? :)

**Comment by lalotone** [comment]
Yes, of course. :)

**Comment by muesli** [comment]
@lalotone @rubiojr I just added both of you to the collaborator's list. This should give you write access to the Wiki. Please add your bees to the "Available Bees" page. Thanks again!

I'd still recommend sending in Pull Requests instead of directly pushing to the git repo for patches though. This guarantees someone will review them.

**Comment by lalotone** [comment]
Perfect! I'll change the Wiki with our bees and some info about them.

**Pull request merged**
