### PR TITLE
Attempt to fix Facebook auth scopes (#264)

### PR DESCRIPTION
**Pull request by pbek**

### CODE REVIEW

**Comment by pbek** [comment]
Follow up from #345.

> Have you tried authing with Facebook with the new app scope?

I now have setup my own build and docker deployment process so I can test on my server.
After the painful configuration at https://developers.facebook.com (and successifuly receiving an auth token) I'm one step further.

```
ERRO[0993] [Facebook 2]: Error: [message:(#200) If posting to a group, requires app being installed in the group, and \
          either publish_to_groups permission with user token, or both pages_read_engagement \
          and pages_manage_posts permission with page token; If posting to a page, \
          requires both pages_read_engagement and pages_manage_posts as an admin with \
          sufficient administrative permission] [type:OAuthException] [code:200] [subcode:0] 
```

So yes, the scopes are working.

**Comment by pbek** [comment]
@muesli, is the Facebook Hive capable of posting to a Facebook page? Because that's what I'm trying to achieve. 😀

**Comment by pbek** [comment]
It seems like pages are a different thing, you need a page access token, https://developers.facebook.com/docs/pages/publishing.

**Comment by muesli** [comment]
I must admit I've kinda stopped using Facebook personally, but have so far only used it to post on my personal page - which Facebook now doesn't permit anymore.

Posting to pages via the API should still be doable, though. We may or may not have to adapt to their newer API versions.

**Comment by pbek** [comment]
Facebook posting was always kind of flaky (back a few years ago when I wrote my own publishing integration) since access tokens seem to expire from time to time...

**Review by muesli — APPROVED** [review]

**Comment by muesli** [comment]
Thank you, @pbek!

**Pull request merged**
