### PR TITLE
Bump upstream telegram package

### PR DESCRIPTION
**Pull request by rubiojr**
And some minor tweaks to logging.

### CODE REVIEW

**Comment by muesli** [comment]
I'm a bit confused by that change. Isn't that lowering the `telegram-bot-api` version?

**Comment by rubiojr** [comment]
> I'm a bit confused by that change. Isn't that lowering the `telegram-bot-api` version?

Yes, I'm having the same question, the SHA1, matches master from yesterday though. Trying to figure out what I'm missing.

**Comment by rubiojr** [comment]
I won't pretend to fully understand what's going on here, but it's explained in https://tip.golang.org/cmd/go/#hdr-Pseudo_versions

This is the result of `go get github.com/go-telegram-bot-api/telegram-bot-api@5e339ed016b0c7349c092f9fc0ecdf9e18c5f963` or `go get github.com/go-telegram-bot-api/telegram-bot-api@master`.

**Comment by rubiojr** [comment]
@muesli ye :ok_hand: with me merging this?

**Comment by muesli** [comment]
@rubiojr Instead of replying "yes", I decided to just click the button 😂

**Pull request merged**
