### PR TITLE
Adding Transmission bee

### PR DESCRIPTION
**Pull request by lalotone**
Adding torrents to [Transmission](https://transmissionbt.com/) via Transmission's API.

### CODE REVIEW

**Comment by muesli** [comment]
Love it! Just in case you guys like IRC, too, feel free to join me/us on freenode, channel #beehive.

**Comment by muesli** [comment]
I just realized that for some reason the actions this bee offers aren't listed on startup. Is it showing up fine for you?

===

2016/12/06 19:02:04 Bee Factory ready: transmissionbee - A bee for adding torrents to a transmission server
2016/12/06 19:02:04 
2016/12/06 19:02:04 Bee Factory ready: tumblrbee - A Tumblr module for beehive

**Comment by muesli** [comment]
Ok, pretty obvious once I took a closer look. The Actions method wasn't part of the Factory. I pushed a fix.

**Comment by rubiojr** [comment]
Missed that, thanks for the fix!

**Pull request merged**
