### PR TITLE
Telegram bee updates

### PR DESCRIPTION
**Pull request by rubiojr**
This a backwards compatible change, existing installs shouldn't note the difference.

### Switch to [tucnak/telebot](https://github.com/tucnak/telebot)

Nice, cleaner API and they seem to be doing a better job at releasing software.

### Optional HTML parsing for messages

New option to enable [HTML formatting](https://core.telegram.org/bots/api#html-style), implementing a feature request in https://github.com/muesli/beehive/issues/308 (disabled by default). cc @it-parasite

### CODE REVIEW

**Comment by muesli** [comment]
Nice! Only downside I see right now is the new package requiring Go 1.12+. I'm happy to bump that though.

**Comment by rubiojr** [comment]
@muesli :+1:  up to you. We can keep this open till Go is bumped. Or I can do that too, let me know.

**Comment by muesli** [comment]
Yeah, let's just bump it. I'll adjust the CI first, then we can re-run the tests and merge this.

**Comment by muesli** [comment]
Sorry for the conflicts I introduced 🙈

**Comment by rubiojr** [comment]
I'll have a look!

**Comment by rubiojr** [comment]
This work is happening in Beehive's rewrite (https://github.com/muesli/beehive/issues/390#issuecomment-1041179887), so closing as this will (likely) never be addressed here.

**Pull request closed without merging**
