### PR TITLE
Fix Twitter 100% CPU (#335)

### PR DESCRIPTION
**Pull request by pbek**
This fixes the 100% CPU problem of https://github.com/muesli/beehive/issues/335.

- Posting a tweet still works
- Reacting to a like still doesn't work

### CODE REVIEW

**Comment by muesli** [comment]
I'm not sure that's the right fix: the sleep certainly prevents it from using all of your CPU, but it looping constantly means there's something else going wrong. It's probably because the user-stream API has pretty much been shutdown by Twitter. I guess we can remove it from Beehive altogether now.

**Comment by pbek** [comment]
Posting still works! see #335

**Comment by muesli** [comment]
Oh sorry, I didn't mean to remove the Twitter hive entirely. I only meant to remove the user stream from the code.

**Comment by muesli** [comment]
Replaced by #348.

**Pull request closed without merging**
