### PR TITLE
Use Gopkg.toml for dependencies

### PR DESCRIPTION
**Pull request by asymmetric**
See muesli/beehive-vendor#2 for a discussion.

### CODE REVIEW

**Comment by muesli** [comment]
I think we need to ensure a different gomail version: See branch v1 vs v2.

**Comment by asymmetric** [comment]
Another problem is that it has been moved, and I'm not sure `dep` is able to deal with it.

**Comment by asymmetric** [comment]
`curl` [failed](https://travis-ci.org/muesli/beehive/jobs/351351283) on OSX for some reason, so I used `brew`.

**Comment by muesli** [comment]
Nice, looks good to me at first glance. I'm going to give it a quick spin tonight and will merge it (unless there's an issue, of course).

**Comment by asymmetric** [comment]
Did you have a chance to take a look at this?

**Comment by muesli** [comment]
Yeah, I'm really happy with all those changes! Nice work! Merge incoming.

**Pull request merged**
