### PR TITLE
Test template filters

### PR DESCRIPTION
**Pull request by orsinium**
1. Make template filters kind of type-safe. leave type reflection to the template engine and accept already the right type. Also, it helps to correctly match the number of arguments, making error messages in that case user-friendly.
2. Add unit tests for happy-path for custom filters.
3. Do not suppress errors from filters, making them propagate up into the template engine. The engine gracefully handles it and returns as the second argument from `Template.Execute` method indicating template execution failure.

Thank you for the amazing project! I'm migrating from IFTTT :)

### CODE REVIEW

**Comment by orsinium** [comment]
CI fails not because of my changes, I'm sure. Is it flaky? :thinking:

**Comment by rocket357** [comment]
Yes. I put in a PR for docker and CI failed for windows! The docker file
isnt (to my knowledge) used or touched in the CI builds. So I would assume
CI is flakey.

**Comment by muesli** [comment]
Just a heads up: @penguwin is already working on fixing the Windows builds.

**Comment by muesli** [comment]
Great contribution, thank you!

**Pull request merged**
